backend/
.git
.gitignore

Dockerfile
docker-compose.yml
coverage

**/node_modules/
backend/node_modules/
frontend/node_modules/
lib/node_modules/

.env
*.log

**/tests/**

.vscode
.DS_Store
dist/
build/